update_chats_count_job:
  cron: "*/5 * * * *"    # every 5 minutes
  class: "UpdateChatsCountJob"
  queue: default

update_messages_count_job:
  cron: "*/5 * * * *"     # every 5 minutes
  class: "UpdateMessagesCountJob"
  queue: default